## Standard
set_property IOSTANDARD LVCMOS33 [get_ports *]

## Location
## External Clock(50MHz)
set_property PACKAGE_PIN D18  [get_ports EXTCLK50M]
## AT93C46D
set_property PACKAGE_PIN U4   [get_ports EEPROM_CS]
set_property PACKAGE_PIN U2   [get_ports EEPROM_SK]
set_property PACKAGE_PIN U1   [get_ports EEPROM_DI]
set_property PACKAGE_PIN T4   [get_ports EEPROM_DO]
## PHY(100Mbps only)
set_property PACKAGE_PIN J3   [get_ports ETH_RSTn   ]
set_property PACKAGE_PIN N3   [get_ports ETH_TX_CLK ]
set_property PACKAGE_PIN M1   [get_ports ETH_TX_EN  ]
set_property PACKAGE_PIN L3   [get_ports ETH_TXD[0] ]
set_property PACKAGE_PIN L4   [get_ports ETH_TXD[1] ]
set_property PACKAGE_PIN L2   [get_ports ETH_TXD[2] ]
set_property PACKAGE_PIN K3   [get_ports ETH_TXD[3] ]
set_property PACKAGE_PIN J1   [get_ports ETH_TX_ER  ]
set_property PACKAGE_PIN R3   [get_ports ETH_RX_CLK ]
set_property PACKAGE_PIN N1   [get_ports ETH_RX_DV  ]
set_property PACKAGE_PIN P1   [get_ports ETH_RXD[0] ]
set_property PACKAGE_PIN P4   [get_ports ETH_RXD[1] ]
set_property PACKAGE_PIN R1   [get_ports ETH_RXD[2] ]
set_property PACKAGE_PIN R2   [get_ports ETH_RXD[3] ]
set_property PACKAGE_PIN M2   [get_ports ETH_RX_ER  ]
set_property PACKAGE_PIN K1   [get_ports ETH_CRS    ]
set_property PACKAGE_PIN K2   [get_ports ETH_COL    ]
set_property PACKAGE_PIN T2   [get_ports ETH_MDC    ]
set_property PACKAGE_PIN T3   [get_ports ETH_MDIO   ]
## EASIROC1
## Direct Control
set_property PACKAGE_PIN D23  [get_ports EASIROC1_HOLDB    ]
set_property PACKAGE_PIN B20  [get_ports EASIROC1_RESET_PA ]
set_property PACKAGE_PIN A20  [get_ports EASIROC1_PWR_ON   ]
set_property PACKAGE_PIN C21  [get_ports EASIROC1_VAL_EVT  ]
set_property PACKAGE_PIN E21  [get_ports EASIROC1_RAZ_CHN  ]
## Slow Control
set_property PACKAGE_PIN B25  [get_ports EASIROC1_CLK_SR   ]
set_property PACKAGE_PIN A24  [get_ports EASIROC1_RSTB_SR  ]
set_property PACKAGE_PIN A25  [get_ports EASIROC1_SRIN_SR  ]
##EASIROC1_SROUT_SR
set_property PACKAGE_PIN B26  [get_ports EASIROC1_LOAD_SC   ]
set_property PACKAGE_PIN A22  [get_ports EASIROC1_SELECT_SC ]
## read register
set_property PACKAGE_PIN C23  [get_ports EASIROC1_CLK_READ   ]
set_property PACKAGE_PIN B24  [get_ports EASIROC1_RSTB_READ  ]
set_property PACKAGE_PIN A23  [get_ports EASIROC1_SRIN_READ  ]
##EASIROC1_SROUT_READ
## ADC
set_property PACKAGE_PIN J26  [get_ports EASIROC1_ADC_CLK_HG]
set_property PACKAGE_PIN D25  [get_ports EASIROC1_ADC_DATA_HG[0] ]
set_property PACKAGE_PIN D26  [get_ports EASIROC1_ADC_DATA_HG[1] ]
set_property PACKAGE_PIN E25  [get_ports EASIROC1_ADC_DATA_HG[2] ]
set_property PACKAGE_PIN E26  [get_ports EASIROC1_ADC_DATA_HG[3] ]
set_property PACKAGE_PIN F24  [get_ports EASIROC1_ADC_DATA_HG[4] ]
set_property PACKAGE_PIN F25  [get_ports EASIROC1_ADC_DATA_HG[5] ]
set_property PACKAGE_PIN G24  [get_ports EASIROC1_ADC_DATA_HG[6] ]
set_property PACKAGE_PIN G25  [get_ports EASIROC1_ADC_DATA_HG[7] ]
set_property PACKAGE_PIN G26  [get_ports EASIROC1_ADC_DATA_HG[8] ]
set_property PACKAGE_PIN H24  [get_ports EASIROC1_ADC_DATA_HG[9] ]
set_property PACKAGE_PIN H26  [get_ports EASIROC1_ADC_DATA_HG[10]]
set_property PACKAGE_PIN J24  [get_ports EASIROC1_ADC_DATA_HG[11]]
set_property PACKAGE_PIN J25  [get_ports EASIROC1_ADC_OTR_HG ]
set_property PACKAGE_PIN G20  [get_ports EASIROC1_ADC_CLK_LG ]
set_property PACKAGE_PIN J14  [get_ports EASIROC1_ADC_DATA_LG[0] ]
set_property PACKAGE_PIN K15  [get_ports EASIROC1_ADC_DATA_LG[1] ]
set_property PACKAGE_PIN J15  [get_ports EASIROC1_ADC_DATA_LG[2] ]
set_property PACKAGE_PIN K16  [get_ports EASIROC1_ADC_DATA_LG[3] ]
set_property PACKAGE_PIN J16  [get_ports EASIROC1_ADC_DATA_LG[4] ]
set_property PACKAGE_PIN K17  [get_ports EASIROC1_ADC_DATA_LG[5] ]
set_property PACKAGE_PIN K18  [get_ports EASIROC1_ADC_DATA_LG[6] ]
set_property PACKAGE_PIN J18  [get_ports EASIROC1_ADC_DATA_LG[7] ]
set_property PACKAGE_PIN H18  [get_ports EASIROC1_ADC_DATA_LG[8] ]
set_property PACKAGE_PIN J19  [get_ports EASIROC1_ADC_DATA_LG[9] ]
set_property PACKAGE_PIN H19  [get_ports EASIROC1_ADC_DATA_LG[10]]
set_property PACKAGE_PIN K20  [get_ports EASIROC1_ADC_DATA_LG[11]]
set_property PACKAGE_PIN J20  [get_ports EASIROC1_ADC_OTR_LG ]
set_property IOB true [get_ports EASIROC1_ADC_DATA_HG]
set_property IOB true [get_ports EASIROC1_ADC_DATA_LG]
set_property IOB true [get_ports EASIROC1_ADC_OTR_HG]
set_property IOB true [get_ports EASIROC1_ADC_OTR_LG]
## TDC
set_property PACKAGE_PIN T25  [get_ports EASIROC1_TRIGGER[0] ]
set_property PACKAGE_PIN T24  [get_ports EASIROC1_TRIGGER[1] ]
set_property PACKAGE_PIN T23  [get_ports EASIROC1_TRIGGER[2] ]
set_property PACKAGE_PIN R26  [get_ports EASIROC1_TRIGGER[3] ]
set_property PACKAGE_PIN R25  [get_ports EASIROC1_TRIGGER[4] ]
set_property PACKAGE_PIN R23  [get_ports EASIROC1_TRIGGER[5] ]
set_property PACKAGE_PIN P26  [get_ports EASIROC1_TRIGGER[6] ]
set_property PACKAGE_PIN P25  [get_ports EASIROC1_TRIGGER[7] ]
set_property PACKAGE_PIN P24  [get_ports EASIROC1_TRIGGER[8] ]
set_property PACKAGE_PIN P23  [get_ports EASIROC1_TRIGGER[9] ]
set_property PACKAGE_PIN N26  [get_ports EASIROC1_TRIGGER[10]]
set_property PACKAGE_PIN N24  [get_ports EASIROC1_TRIGGER[11]]
set_property PACKAGE_PIN N23  [get_ports EASIROC1_TRIGGER[12]]
set_property PACKAGE_PIN M26  [get_ports EASIROC1_TRIGGER[13]]
set_property PACKAGE_PIN M25  [get_ports EASIROC1_TRIGGER[14]]
set_property PACKAGE_PIN M24  [get_ports EASIROC1_TRIGGER[15]]
set_property PACKAGE_PIN L25  [get_ports EASIROC1_TRIGGER[16]]
set_property PACKAGE_PIN L24  [get_ports EASIROC1_TRIGGER[17]]
set_property PACKAGE_PIN L23  [get_ports EASIROC1_TRIGGER[18]]
set_property PACKAGE_PIN L22  [get_ports EASIROC1_TRIGGER[19]]
set_property PACKAGE_PIN K26  [get_ports EASIROC1_TRIGGER[20]]
set_property PACKAGE_PIN K25  [get_ports EASIROC1_TRIGGER[21]]
set_property PACKAGE_PIN M20  [get_ports EASIROC1_TRIGGER[22]]
set_property PACKAGE_PIN P20  [get_ports EASIROC1_TRIGGER[23]]
set_property PACKAGE_PIN R20  [get_ports EASIROC1_TRIGGER[24]]
set_property PACKAGE_PIN N19  [get_ports EASIROC1_TRIGGER[25]]
set_property PACKAGE_PIN P19  [get_ports EASIROC1_TRIGGER[26]]
set_property PACKAGE_PIN N18  [get_ports EASIROC1_TRIGGER[27]]
set_property PACKAGE_PIN N17  [get_ports EASIROC1_TRIGGER[28]]
set_property PACKAGE_PIN R17  [get_ports EASIROC1_TRIGGER[29]]
set_property PACKAGE_PIN N16  [get_ports EASIROC1_TRIGGER[30]]
set_property PACKAGE_PIN R16  [get_ports EASIROC1_TRIGGER[31]]
## EASIROC2
## Direct Control
set_property PACKAGE_PIN D20  [get_ports EASIROC2_HOLDB    ]
set_property PACKAGE_PIN C17  [get_ports EASIROC2_RESET_PA ]
set_property PACKAGE_PIN E17  [get_ports EASIROC2_PWR_ON   ]
set_property PACKAGE_PIN G16  [get_ports EASIROC2_VAL_EVT  ]
set_property PACKAGE_PIN D16  [get_ports EASIROC2_RAZ_CHN  ]
## Slow Control
set_property PACKAGE_PIN A18  [get_ports EASIROC2_CLK_SR   ]
set_property PACKAGE_PIN D19  [get_ports EASIROC2_RSTB_SR  ]
set_property PACKAGE_PIN E18  [get_ports EASIROC2_SRIN_SR  ]
##EASIROC2_SROUT_SR
set_property PACKAGE_PIN B17  [get_ports EASIROC2_LOAD_SC   ]
set_property PACKAGE_PIN H15  [get_ports EASIROC2_SELECT_SC ]
## read register
set_property PACKAGE_PIN E20  [get_ports EASIROC2_CLK_READ  ]
set_property PACKAGE_PIN C19  [get_ports EASIROC2_RSTB_READ ]
set_property PACKAGE_PIN A19  [get_ports EASIROC2_SRIN_READ ]
##EASIROC2_SROUT_READ
## ADC
set_property PACKAGE_PIN A5   [get_ports EASIROC2_ADC_CLK_HG ]
set_property PACKAGE_PIN C1   [get_ports EASIROC2_ADC_DATA_HG[0] ]
set_property PACKAGE_PIN B1   [get_ports EASIROC2_ADC_DATA_HG[1] ]
set_property PACKAGE_PIN C2   [get_ports EASIROC2_ADC_DATA_HG[2] ]
set_property PACKAGE_PIN B2   [get_ports EASIROC2_ADC_DATA_HG[3] ]
set_property PACKAGE_PIN A2   [get_ports EASIROC2_ADC_DATA_HG[4] ]
set_property PACKAGE_PIN C3   [get_ports EASIROC2_ADC_DATA_HG[5] ]
set_property PACKAGE_PIN A3   [get_ports EASIROC2_ADC_DATA_HG[6] ]
set_property PACKAGE_PIN C4   [get_ports EASIROC2_ADC_DATA_HG[7] ]
set_property PACKAGE_PIN B4   [get_ports EASIROC2_ADC_DATA_HG[8] ]
set_property PACKAGE_PIN A4   [get_ports EASIROC2_ADC_DATA_HG[9] ]
set_property PACKAGE_PIN E5   [get_ports EASIROC2_ADC_DATA_HG[10]]
set_property PACKAGE_PIN D5   [get_ports EASIROC2_ADC_DATA_HG[11]]
set_property PACKAGE_PIN B5   [get_ports EASIROC2_ADC_OTR_HG  ]
set_property PACKAGE_PIN D1   [get_ports EASIROC2_ADC_CLK_LG  ]
set_property PACKAGE_PIN H4   [get_ports EASIROC2_ADC_DATA_LG[0] ]
set_property PACKAGE_PIN H3   [get_ports EASIROC2_ADC_DATA_LG[1] ]
set_property PACKAGE_PIN G4   [get_ports EASIROC2_ADC_DATA_LG[2] ]
set_property PACKAGE_PIN G2   [get_ports EASIROC2_ADC_DATA_LG[3] ]
set_property PACKAGE_PIN G1   [get_ports EASIROC2_ADC_DATA_LG[4] ]
set_property PACKAGE_PIN F4   [get_ports EASIROC2_ADC_DATA_LG[5] ]
set_property PACKAGE_PIN F3   [get_ports EASIROC2_ADC_DATA_LG[6] ]
set_property PACKAGE_PIN F2   [get_ports EASIROC2_ADC_DATA_LG[7] ]
set_property PACKAGE_PIN E3   [get_ports EASIROC2_ADC_DATA_LG[8] ]
set_property PACKAGE_PIN E2   [get_ports EASIROC2_ADC_DATA_LG[9] ]
set_property PACKAGE_PIN E1   [get_ports EASIROC2_ADC_DATA_LG[10]]
set_property PACKAGE_PIN D4   [get_ports EASIROC2_ADC_DATA_LG[11]]
set_property PACKAGE_PIN D3   [get_ports EASIROC2_ADC_OTR_LG ]
set_property IOB true [get_ports EASIROC2_ADC_DATA_HG]
set_property IOB true [get_ports EASIROC2_ADC_DATA_LG]
set_property IOB true [get_ports EASIROC2_ADC_OTR_HG]
set_property IOB true [get_ports EASIROC2_ADC_OTR_LG]
## TDC
set_property PACKAGE_PIN U24  [get_ports EASIROC2_TRIGGER[0] ]
set_property PACKAGE_PIN U25  [get_ports EASIROC2_TRIGGER[1] ]
set_property PACKAGE_PIN U26  [get_ports EASIROC2_TRIGGER[2] ]
set_property PACKAGE_PIN V24  [get_ports EASIROC2_TRIGGER[3] ]
set_property PACKAGE_PIN V26  [get_ports EASIROC2_TRIGGER[4] ]
set_property PACKAGE_PIN W24  [get_ports EASIROC2_TRIGGER[5] ]
set_property PACKAGE_PIN W25  [get_ports EASIROC2_TRIGGER[6] ]
set_property PACKAGE_PIN W26  [get_ports EASIROC2_TRIGGER[7] ]
set_property PACKAGE_PIN Y25  [get_ports EASIROC2_TRIGGER[8] ]
set_property PACKAGE_PIN Y26  [get_ports EASIROC2_TRIGGER[9] ]
set_property PACKAGE_PIN AA25 [get_ports EASIROC2_TRIGGER[10]]
set_property PACKAGE_PIN AB26 [get_ports EASIROC2_TRIGGER[11]]
set_property PACKAGE_PIN AC26 [get_ports EASIROC2_TRIGGER[12]]
set_property PACKAGE_PIN AB25 [get_ports EASIROC2_TRIGGER[13]]
set_property PACKAGE_PIN AA24 [get_ports EASIROC2_TRIGGER[14]]
set_property PACKAGE_PIN AB24 [get_ports EASIROC2_TRIGGER[15]]
set_property PACKAGE_PIN AC24 [get_ports EASIROC2_TRIGGER[16]]
set_property PACKAGE_PIN W23  [get_ports EASIROC2_TRIGGER[17]]
set_property PACKAGE_PIN Y23  [get_ports EASIROC2_TRIGGER[18]]
set_property PACKAGE_PIN AA23 [get_ports EASIROC2_TRIGGER[19]]
set_property PACKAGE_PIN Y22  [get_ports EASIROC2_TRIGGER[20]]
set_property PACKAGE_PIN AA22 [get_ports EASIROC2_TRIGGER[21]]
set_property PACKAGE_PIN W21  [get_ports EASIROC2_TRIGGER[22]]
set_property PACKAGE_PIN Y21  [get_ports EASIROC2_TRIGGER[23]]
set_property PACKAGE_PIN W20  [get_ports EASIROC2_TRIGGER[24]]
set_property PACKAGE_PIN Y20  [get_ports EASIROC2_TRIGGER[25]]
set_property PACKAGE_PIN U19  [get_ports EASIROC2_TRIGGER[26]]
set_property PACKAGE_PIN V19  [get_ports EASIROC2_TRIGGER[27]]
set_property PACKAGE_PIN W19  [get_ports EASIROC2_TRIGGER[28]]
set_property PACKAGE_PIN V18  [get_ports EASIROC2_TRIGGER[29]]
set_property PACKAGE_PIN W18  [get_ports EASIROC2_TRIGGER[30]]
set_property PACKAGE_PIN V17  [get_ports EASIROC2_TRIGGER[31]]
## DIP SW
set_property PACKAGE_PIN R8   [get_ports DIP_SW[0]]
## SPI FLASH
##set_property PACKAGE_PIN L15  [get_ports SPI_SCLK ]
set_property PACKAGE_PIN P14  [get_ports SPI_SCLK ]
set_property PACKAGE_PIN P18  [get_ports SPI_SS_N ]
set_property PACKAGE_PIN R14  [get_ports SPI_MOSI ]
set_property PACKAGE_PIN R15  [get_ports SPI_MISO ]
set_property PACKAGE_PIN M19  [get_ports PROG_B_ON]
set_property IOB true [get_ports SPI_SCLK]
set_property IOB true [get_ports SPI_SS_N]
set_property IOB true [get_ports SPI_MOSI]
set_property IOB true [get_ports SPI_MISO]
set_property IOB true [get_ports PROG_B_ON]
## LED Control
set_property PACKAGE_PIN T14  [get_ports LED[1]]
set_property PACKAGE_PIN T17  [get_ports LED[2]]
set_property PACKAGE_PIN U15  [get_ports LED[3]]
set_property PACKAGE_PIN V14  [get_ports LED[4]]
set_property PACKAGE_PIN V16  [get_ports LED[5]]
set_property PACKAGE_PIN U16  [get_ports LED[6]]
set_property PACKAGE_PIN U14  [get_ports LED[7]]
set_property PACKAGE_PIN T15  [get_ports LED[8]]
## Test charge injection
set_property PACKAGE_PIN F17  [get_ports CAL1    ]
set_property PACKAGE_PIN F18  [get_ports CAL2    ]
set_property PACKAGE_PIN T8   [get_ports PWR_RST ]
## Monitor ADC
set_property PACKAGE_PIN F8   [get_ports MUX[0]   ]
set_property PACKAGE_PIN G8   [get_ports MUX[1]   ]
set_property PACKAGE_PIN F7   [get_ports MUX[2]   ]
set_property PACKAGE_PIN G7   [get_ports MUX[3]   ]
set_property PACKAGE_PIN E6   [get_ports MUX_EN[0]]
set_property PACKAGE_PIN H9   [get_ports MUX_EN[1]]
set_property PACKAGE_PIN D6   [get_ports MUX_EN[2]]
set_property PACKAGE_PIN G9   [get_ports MUX_EN[3]]
set_property PACKAGE_PIN J6   [get_ports CS_MADC  ]
set_property PACKAGE_PIN K8   [get_ports DIN_MADC ]
set_property PACKAGE_PIN L8   [get_ports SCK_MADC ]
set_property PACKAGE_PIN K6   [get_ports DOUT_MADC]
## SiTCP
set_property PACKAGE_PIN H1   [get_ports ETH_LED[1]]
set_property PACKAGE_PIN H2   [get_ports ETH_LED[2]]
## HV Control
set_property PACKAGE_PIN M7   [get_ports SCK_DAC]
set_property PACKAGE_PIN L7   [get_ports SDI_DAC]
set_property PACKAGE_PIN M6   [get_ports CS_DAC ]
set_property PACKAGE_PIN N6   [get_ports HV_EN  ]
## User I/O
set_property PACKAGE_PIN T22  [get_ports IN_FPGA[1]     ]
set_property PACKAGE_PIN R22  [get_ports IN_FPGA[2]     ]
set_property PACKAGE_PIN R21  [get_ports IN_FPGA[3]     ]
set_property PACKAGE_PIN P21  [get_ports IN_FPGA[4]     ]
set_property PACKAGE_PIN N21  [get_ports IN_FPGA[5]     ]
set_property PACKAGE_PIN M21  [get_ports IN_FPGA[6]     ]
set_property PACKAGE_PIN T5   [get_ports OUT_FPGA[1]    ]
set_property PACKAGE_PIN U5   [get_ports OUT_FPGA[2]    ]
set_property PACKAGE_PIN R6   [get_ports OUT_FPGA[3]    ]
set_property PACKAGE_PIN U6   [get_ports OUT_FPGA[4]    ]
set_property PACKAGE_PIN R7   [get_ports OUT_FPGA[5]    ]
set_property PACKAGE_PIN B22  [get_ports OR32_C1        ]
set_property PACKAGE_PIN G15  [get_ports OR32_C2        ]
set_property PACKAGE_PIN C22  [get_ports DIGITAL_LINE_C1]
set_property PACKAGE_PIN F15  [get_ports DIGITAL_LINE_C2]

## Pullup, Pulldown
set_property PULLUP true [get_ports ETH_COL]
set_property PULLUP true [get_ports ETH_RXD[0]]
set_property PULLUP true [get_ports ETH_RXD[1]]
set_property PULLDOWN true [get_ports ETH_RXD[2]]
set_property PULLDOWN true [get_ports ETH_RXD[3]]
set_property PULLDOWN true [get_ports ETH_RX_CLK]
set_property PULLDOWN true [get_ports ETH_RX_ER]
set_property PULLDOWN true [get_ports DIP_SW[0]]
